name: 'Tofu'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

env:
  TF_VAR_projectid: myanthosproject2
  TF_VAR_bucketname: mytestbucket223344

jobs:
  tofu:
    name: 'Tofu'
    runs-on: self-hosted
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        token_format: "access_token"
        create_credentials_file: true
        activate_credentials_file: true
        workload_identity_provider: 'projects/511842454269/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: 'test-wif@myanthosproject2.iam.gserviceaccount.com'
        access_token_lifetime: '100s'
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Tofu Init
      run: tofu init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Tofu Format
      run: tofu fmt -check

    # TF Validate
    - name: Tofu Validate
      run: tofu validate

    # Generates an execution plan for Terraform
    - name: Tofu Plan
      run: tofu plan -input=false

      # On push to "main", build or change infrastructure according to Tofu configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Tofu Apply
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/remotes/origin/main' || github.ref == 'main'
      run: tofu apply -auto-approve -input=false
